channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.7
  - dask>=2.29.0
  - coiled=0.0.25
  - numpy
  - pandas>=1.1.0
  - dask-ml
  - skorch
  - scipy
  - matplotlib
  - pytorch>1.1.0
  - s3fs