channels:
- conda-forge
- pytorch
- defaults
dependencies:
- python=3.8
- dask=2021.4.0
- coiled=0.0.38
- numpy
- pandas>=1.1.0
- skorch
- scipy
- matplotlib
- pytorch>1.1.0
- s3fs
- pip:
  # Can remove this pin when dask-ml > 1.8.0 is released.
  - git+https://github.com/dask/dask-ml@0ea276da1d78db582f40e1c256dfca4f70e6cbc6
