name: Check for new Coiled version on conda-forge

on:
  schedule:
    - cron: "0 * * * *"

jobs:
  check-version:
    runs-on: ubuntu-latest
    if: github.repository == 'coiled/notebooks'

    steps:
      - uses: actions/checkout@v2
      - name: Get latest Coiled version
        id: latest_version
        uses: jacobtomlinson/gha-anaconda-package-version@0.1.1
        with:
          org: "conda-forge"
          package: "coiled"

      - name: Find and replace Coiled version
        id: find_and_replace
        uses: jacobtomlinson/gha-find-replace@0.1.1
        with:
          find: "coiled=*([\d.]+)"
          replace: "coiled=${{ steps.latest_version.outputs.version }} "

      - name: Output changed files
        run: echo ${{ steps.find_and_replace.outputs.modifiedFiles }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Update Coiled version to ${{ steps.latest_version.outputs.version }}"
          title: "Update Coiled version to ${{ steps.latest_version.outputs.version }}"
          reviewers: "jrbourbeau"
          branch: "upgrade-package-versions"
          body: |
            A new Coiled version has been detected.

            Updated Coiled to `${{ steps.latest_version.outputs.version }}`.
