name: Check for new dask version on conda-forge

on:
  schedule:
    - cron: "36 * * * *"

jobs:
  check-version:
    runs-on: ubuntu-latest
    if: github.repository == 'coiled/notebooks'

    steps:
      - uses: actions/checkout@v2
      - name: Get latest dask version
        id: latest_version
        uses: jacobtomlinson/gha-anaconda-package-version@0.1.1
        with:
          org: "conda-forge"
          package: "dask"

      - name: Find and replace dask version
        id: find_and_replace
        uses: jacobtomlinson/gha-find-replace@0.1.1
        with:
          find: "dask=.*[0-9]+"
          replace: "dask=${{ steps.latest_version.outputs.version }}"
          include: "create-notebook.py"

      - name: Output changed files
        run: echo ${{ steps.find_and_replace.outputs.modifiedFiles }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Update dask version to ${{ steps.latest_version.outputs.version }}"
          title: "Update dask version to ${{ steps.latest_version.outputs.version }}"
          reviewers: "jrbourbeau,ian-r-rose"
          branch: "upgrade-package-versions"
          body: |
            A new dask version has been detected.

            Updated dask to `${{ steps.latest_version.outputs.version }}`.
