
name: Build notebooks

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DASK_COILED__SERVER: https://cloud.coiled.io
      DASK_COILED__TOKEN: ${{ secrets.DASK_COILED__TOKEN }}

    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v1

      - name: Install Coiled
        run: python -m pip install coiled

      - name: Build notebooks
        run: |
          python quickstart/create-notebook.py
          python scaling-xgboost/create-notebook.py
          python optuna-xgboost/create-notebook.py
          python jupyterlab/create-notebook.py