
name: Build notebooks

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DASK_COILED__SERVER: https://cloud.coiled.io
      DASK_COILED__TOKEN: ${{ secrets.DASK_COILED__TOKEN }}

    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v1

      - name: Install Coiled
        run: python -m pip install coiled

      - name: Build quickstart notebook
        run: python quickstart/create-notebook.py
        working-directory: quickstart

      - name: Build scaling xgboost notebook
        run: python scaling-xgboost/create-notebook.py
        working-directory: scaling-xgboost

      - name: Build optuna notebook
        run: python optuna-xgboost/create-notebook.py
        working-directory: optuna-xgboost

      - name: Build jupyterlab notebook
        run: python jupyterlab/create-notebook.py
        working-directory: jupyterlab