name: Build notebooks

on:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        example:
          [
            "quickstart",
            "scaling-xgboost",
            "optuna-xgboost",
            "jupyterlab",
            "hyperband",
            "dask-sql",
          ]
        server: ["https://cloud.coiled.io", "https://staging.coiledhq.com"]
        include:
          - server: "https://cloud.coiled.io"
            token-name: CLOUD_TOKEN

          - server: "https://staging.coiledhq.com"
            token-name: SANDBOX_TOKEN
    env:
      DASK_COILED__SERVER: ${{ matrix.server }}
      DASK_COILED__TOKEN: ${{ secrets[matrix.token-name] }}

    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v1

      - name: Install Coiled
        run: python -m pip install coiled

      - name: Build ${{ matrix.example }} notebook
        run: python create-notebook.py
        working-directory: ${{ matrix.example }}
